python:
  - name: requests
    include_prereleases: false
  - name: numpy
    include_prereleases: false
  - name: fastapi
    include_prereleases: false
  - name: pandas
    include_prereleases: false
  - name: pydantic
    include_prereleases: false
